### ISSUE TITLE
docker image is not up to date

### ISSUE THREAD

**Issue by fdqfdq** [BrainicHQ/tado-assistant#14]
I tried the dock image, and wanted to disable geofencing. But it does not disable it.
I checked and realized that the whole "if [ "$ENABLE_GEOFENCING" == true ]; then" part is not there.
So I think that the docker image is not updated to the current script.
Thanks!

**Comment by s4yanx** [comment]
same here, cant disable geofancing while running in docker.,,,

**Comment by s1lviu** [comment]
Hi, will update tomorrow. Thanks.

**Comment by s1lviu** [comment]
I've just pushed the updated image.
