### ISSUE TITLE
Multi Arch Support

### ISSUE THREAD

**Issue by saschabrockel** [BrainicHQ/tado-assistant#2]
I wanted to try your work but got the following error:
```
WARNING: The requested image's platform (linux/arm64/v8) does not match the detected host platform (linux/amd64) and no specific platform was requested
32fb0b3145eabfc1fff1890a77f7abbc3ef826a941cf2c5e2275c36b39fa2f9c
```

It's really important to support multiple platforms. And linux/amd64 is the most basic one. Do you know how to do it? I lost your mails...

**Comment by s1lviu** [comment]
Hi @saschabrockel,

Please check now. I had done the build on my M1 mac and that's why the problem occurred.

Thanks!

**Comment by saschabrockel** [comment]
Seems to work but I get `/usr/local/bin/tado-assistant.sh: line 51: username_var: invalid indirect expansion` as error in the logs of the container now. Does the username_var needs to be written in ' ' ?

**Comment by s1lviu** [comment]
No, it seems was a bash issue. Should be fixed now: https://github.com/BrainicHQ/tado-assistant/commit/d3ec26e61bc92c5ce03b619e10d111da953014c2

**Comment by saschabrockel** [comment]
Works now!

**Comment by saschabrockel** [comment]
Just one idea. It would be awesome if the timezone could be adjusted. I guess the default is UTC because it is 1 hour back for me. I tried the TZ env variable but it does not work.
