### ISSUE TITLE
System timezone

### ISSUE THREAD

**Issue by s1lviu** [BrainicHQ/tado-assistant#3]
Just one idea. It would be awesome if the timezone could be adjusted. I guess the default is UTC because it is 1 hour back for me. I tried the TZ env variable but it does not work.

_Originally posted by @saschabrockel in https://github.com/BrainicHQ/tado-assistant/issues/2#issuecomment-1871719409_

**Comment by s1lviu** [comment]
@saschabrockel, the script should use the system timezone. Can you double-check if your environment has the right timezone set for that? Thanks!

**Comment by saschabrockel** [comment]
@s1lviu Hmm my system time is correct. I'm using NTP to set timezone and time.
Fri Dec 29 14:48:37 CET 2023

**Comment by s1lviu** [comment]
Do you have any specific Docker settings then?

**Comment by saschabrockel** [comment]
Not that I would know. I'm using it on my UNRAID server.

**Comment by s1lviu** [comment]
Ok. As Docker uses by default UTC timezone, you can run the script with the TZ parameter:

```
docker run -d --name tado-assistant \
        -e TZ='Europe/Berlin' \  
        -e NUM_ACCOUNTS=2 \
        -e TADO_USERNAME_1='your_username_1' \
        -e TADO_PASSWORD_1='your_password_1' \
        -e CHECKING_INTERVAL_1=15 \
        -e ENABLE_LOG_1=true \
        -e LOG_FILE_1=<LOG_FILE_PATH_1> \
        -e MAX_OPEN_WINDOW_DURATION_1= \
        -e TADO_USERNAME_2='your_username_2' \
        -e TADO_PASSWORD_2='your_password_2' \
        -e CHECKING_INTERVAL_2=15 \
        -e ENABLE_LOG_2=true \
        -e LOG_FILE_2=<LOG_FILE_PATH_2> \
        -e MAX_OPEN_WINDOW_DURATION_2= \
        brainic/tado-assistant
```

**Comment by saschabrockel** [comment]
Does it work for you? I tried it with TZ like I said in the beginning but nothing changed.

```
docker run
  -d
  --name='tado-assistant'
  --net='unraid'
  -e TZ="Europe/Berlin"
  -e HOST_OS="Unraid"
  -e HOST_HOSTNAME="UNRAID-Server"
  -e HOST_CONTAINERNAME="tado-assistant"
  -e 'NUM_ACCOUNTS'='1'
  -e 'TADO_USERNAME_1'='xyz'
  -e 'TADO_PASSWORD_1'='xyz'
  -e 'CHECKING_INTERVAL_1'='15'
  -e 'ENABLE_LOG_1'='true'
  -e 'LOG_FILE_1'=''
  -e 'MAX_OPEN_WINDOW_DURATION_1'=''
  -e 'TZ'='Europe/Berlin'
  -l net.unraid.docker.managed=dockerman
  -l net.unraid.docker.icon='https://play-lh.googleusercontent.com/NEKYb6DhXZQy5rFNjWQHrArQWvYRa3xM8MZHIhqbqwiu7wOkr60feA6gaAFwQ5wZtec' 'brainic/tado-assistant'
71cb23bf5f3033dac8af007fc757c59618f8acd96d5f10fe0a2189f31c3a6ab1
```

**Comment by s1lviu** [comment]
For me, it was working without TZ, but I have updated the docker image and now TZ should work fine.

**Comment by saschabrockel** [comment]
Yes! It works now.
