### ISSUE TITLE
Container stops instantly when an error occurs

### ISSUE THREAD

**Issue by saschabrockel** [BrainicHQ/tado-assistant#5]
Is it intended that the container stops when there is an error? I didn't realize it stopped working until I was going out and saw the Tado notification if it should activate the AWAY mode. The last logs:

```
16-01-2024 07:51:12 # ⏳ Account 1: Waiting for a change in devices location or for an open window..
16-01-2024 07:51:28 # 🏠 Account 1: Home is in HOME Mode, the devices XYZ are at home.
16-01-2024 07:51:28 # ⏳ Account 1: Waiting for a change in devices location or for an open window..
16-01-2024 07:51:45 # Curl command failed. Retrying in 60 seconds.
16-01-2024 07:52:45 # ❌ Login error for account 1, check the username / password!
```

I don't have set the restart policy for the container which would also help but I guess it shouldn't be like this because it's also saying retrying.

**Comment by s1lviu** [comment]
Hi @saschabrockel,

Apologies for the delay in responding. In the scenario you've described, the script is designed to exit and should be manually restarted after verifying that the credentials are correct. To make this clearer, I've updated the log message to explicitly mention the need to check the username/password and restart the container or service.

As you rightly pointed out, implementing a Docker restart policy is indeed a good strategy for handling such cases. This approach would automate the restart process, ensuring the container recovers from failures without manual intervention.

Thank you for bringing this to my attention, and please don't hesitate to reach out if you have any more questions or feedback!

Best regards,
Silviu
