### ISSUE TITLE
Login fails

### ISSUE THREAD

**Issue by hairy-dog** [BrainicHQ/tado-assistant#6]
I have two Tado installations, each with a different email address login. I can log in using the email address and password for either of them at tado.com but when I use these in the tado-assistant, it tells me the login is wrong

' Login error for account 1: Please check the username and password. Then restart the container or service.

The credentiials I have set up work in the app, and they work at tado.com. 

However, they do NOT work at auth.tado.com/oauth/token 

Am I doing something wrong?

Also:

I've tried to install it on a pi5 but that fails with an usupported OS error. I've tried it on a pi Zero W and that also fails the same way. 

I am left with running it on a pi4. It installs, it runs, then the login fails as described above.

**Comment by hairy-dog** [comment]
Is there anyone here?

**Comment by blazejpawlak** [comment]
Hey @hairy-dog check out [this PR](https://github.com/BrainicHQ/tado-assistant/pull/7) it might just address your issue.
